
    create table character_parts (
        character_id bigint not null,
        current_health bigint not null,
        id bigint generated by default as identity,
        part_id bigint not null,
        primary key (id)
    );

    create table characters (
        age bigint not null,
        height bigint not null,
        id bigint generated by default as identity,
        ranking_id bigint not null,
        weight bigint not null,
        gender varchar(255) not null,
        name varchar(255) not null unique,
        race varchar(255) not null check (race in ('KANION','ORTHYS','PUMIBLU','FIERCY','ZI_BUM','LENTILLANO','EYESHADE','LUIN','XYRION','CETARA','DENDROLIAN','KEYUI','UNTOLD','SKETCHE','PRIMAL','ROBOT','OTHER')),
        title varchar(255) not null unique,
        primary key (id)
    );

    create table equippable_objects (
        id bigint generated by default as identity,
        power bigint,
        range bigint,
        stealth bigint,
        strength bigint,
        weight bigint,
        description varchar(255),
        name varchar(255) not null unique,
        type varchar(255),
        primary key (id)
    );

    create table items (
        id bigint generated by default as identity,
        price bigint not null,
        description varchar(255),
        name varchar(255) not null unique,
        primary key (id)
    );

    create table parts (
        id bigint generated by default as identity,
        max_health bigint not null,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table paths (
        id bigint generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table ranking_levels (
        id bigint generated by default as identity,
        level bigint not null unique,
        points_required bigint not null,
        description varchar(255),
        primary key (id)
    );

    create table ranks (
        id bigint generated by default as identity,
        level bigint not null unique,
        required_experience bigint not null,
        bonus_descriptions varchar(255),
        primary key (id)
    );

    create table skills (
        is_upgradable boolean,
        id bigint generated by default as identity,
        mental_cost bigint,
        physical_cost bigint,
        required_experience bigint,
        upgrade_level bigint,
        upgrade_points bigint,
        description varchar(255),
        name varchar(255) not null unique,
        primary key (id)
    );

    create table stats (
        abbreviation varchar(3) not null unique,
        id bigint generated by default as identity,
        level_up_experience bigint not null,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table styles (
        id bigint generated by default as identity,
        name varchar(255) not null unique,
        style_class varchar(255) not null unique,
        primary key (id)
    );

    alter table if exists character_parts 
       add constraint FKks74sosw99h4ion8t229aci3j 
       foreign key (character_id) 
       references characters;

    alter table if exists character_parts 
       add constraint FK68ywm1wt4baau1nad9x41029m 
       foreign key (part_id) 
       references parts;

    alter table if exists characters 
       add constraint FK7vg9s6hvmy9u90r7lh3xe7qny 
       foreign key (ranking_id) 
       references ranking_levels;

    create table character_parts (
        character_id bigint not null,
        current_health bigint not null,
        id bigint generated by default as identity,
        part_id bigint not null,
        primary key (id)
    );

    create table characters (
        age bigint not null,
        height bigint not null,
        id bigint generated by default as identity,
        ranking_id bigint not null,
        weight bigint not null,
        gender varchar(255) not null,
        name varchar(255) not null unique,
        race varchar(255) not null check (race in ('KANION','ORTHYS','PUMIBLU','FIERCY','ZI_BUM','LENTILLANO','EYESHADE','LUIN','XYRION','CETARA','DENDROLIAN','KEYUI','UNTOLD','SKETCHE','PRIMAL','ROBOT','OTHER')),
        title varchar(255) not null unique,
        primary key (id)
    );

    create table equippable_objects (
        id bigint generated by default as identity,
        power bigint,
        range bigint,
        stealth bigint,
        strength bigint,
        weight bigint,
        description varchar(255),
        name varchar(255) not null unique,
        type varchar(255),
        primary key (id)
    );

    create table items (
        id bigint generated by default as identity,
        price bigint not null,
        description varchar(255),
        name varchar(255) not null unique,
        primary key (id)
    );

    create table parts (
        id bigint generated by default as identity,
        max_health bigint not null,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table paths (
        id bigint generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table ranking_levels (
        id bigint generated by default as identity,
        level bigint not null unique,
        points_required bigint not null,
        description varchar(255),
        primary key (id)
    );

    create table ranks (
        id bigint generated by default as identity,
        level bigint not null unique,
        required_experience bigint not null,
        bonus_descriptions varchar(255),
        primary key (id)
    );

    create table skills (
        is_upgradable boolean,
        id bigint generated by default as identity,
        mental_cost bigint,
        physical_cost bigint,
        required_experience bigint,
        upgrade_level bigint,
        upgrade_points bigint,
        description varchar(255),
        name varchar(255) not null unique,
        primary key (id)
    );

    create table stats (
        abbreviation varchar(3) not null unique,
        id bigint generated by default as identity,
        level_up_experience bigint not null,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table styles (
        id bigint generated by default as identity,
        name varchar(255) not null unique,
        style_class varchar(255) not null unique,
        primary key (id)
    );

    alter table if exists character_parts 
       add constraint FKks74sosw99h4ion8t229aci3j 
       foreign key (character_id) 
       references characters;

    alter table if exists character_parts 
       add constraint FK68ywm1wt4baau1nad9x41029m 
       foreign key (part_id) 
       references parts;

    alter table if exists characters 
       add constraint FK7vg9s6hvmy9u90r7lh3xe7qny 
       foreign key (ranking_id) 
       references ranking_levels;

    create table character_parts (
        character_id bigint not null,
        current_health bigint not null,
        id bigint generated by default as identity,
        part_id bigint not null,
        primary key (id)
    );

    create table characters (
        age bigint not null,
        height bigint not null,
        id bigint generated by default as identity,
        ranking_id bigint not null,
        weight bigint not null,
        gender varchar(255) not null,
        name varchar(255) not null unique,
        race varchar(255) not null check (race in ('KANION','ORTHYS','PUMIBLU','FIERCY','ZI_BUM','LENTILLANO','EYESHADE','LUIN','XYRION','CETARA','DENDROLIAN','KEYUI','UNTOLD','SKETCHE','PRIMAL','ROBOT','OTHER')),
        title varchar(255) not null unique,
        primary key (id)
    );

    create table equippable_objects (
        id bigint generated by default as identity,
        power bigint,
        range bigint,
        stealth bigint,
        strength bigint,
        weight bigint,
        description varchar(255),
        name varchar(255) not null unique,
        type varchar(255),
        primary key (id)
    );

    create table items (
        id bigint generated by default as identity,
        price bigint not null,
        description varchar(255),
        name varchar(255) not null unique,
        primary key (id)
    );

    create table parts (
        id bigint generated by default as identity,
        max_health bigint not null,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table paths (
        id bigint generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table ranking_levels (
        id bigint generated by default as identity,
        level bigint not null unique,
        points_required bigint not null,
        description varchar(255),
        primary key (id)
    );

    create table ranks (
        id bigint generated by default as identity,
        level bigint not null unique,
        required_experience bigint not null,
        bonus_descriptions varchar(255),
        primary key (id)
    );

    create table skills (
        is_upgradable boolean,
        id bigint generated by default as identity,
        mental_cost bigint,
        physical_cost bigint,
        required_experience bigint,
        upgrade_level bigint,
        upgrade_points bigint,
        description varchar(255),
        name varchar(255) not null unique,
        primary key (id)
    );

    create table stats (
        abbreviation varchar(3) not null unique,
        id bigint generated by default as identity,
        level_up_experience bigint not null,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table styles (
        id bigint generated by default as identity,
        name varchar(255) not null unique,
        style_class varchar(255) not null unique,
        primary key (id)
    );

    alter table if exists character_parts 
       add constraint FKks74sosw99h4ion8t229aci3j 
       foreign key (character_id) 
       references characters;

    alter table if exists character_parts 
       add constraint FK68ywm1wt4baau1nad9x41029m 
       foreign key (part_id) 
       references parts;

    alter table if exists characters 
       add constraint FK7vg9s6hvmy9u90r7lh3xe7qny 
       foreign key (ranking_id) 
       references ranking_levels;

    create table character_parts (
        character_id bigint not null,
        current_health bigint not null,
        id bigint generated by default as identity,
        part_id bigint not null,
        primary key (id)
    );

    create table characters (
        age bigint not null,
        height bigint not null,
        id bigint generated by default as identity,
        ranking_id bigint not null,
        weight bigint not null,
        gender varchar(255) not null,
        name varchar(255) not null unique,
        race varchar(255) not null check (race in ('KANION','ORTHYS','PUMIBLU','FIERCY','ZI_BUM','LENTILLANO','EYESHADE','LUIN','XYRION','CETARA','DENDROLIAN','KEYUI','UNTOLD','SKETCHE','PRIMAL','ROBOT','OTHER')),
        title varchar(255) not null unique,
        primary key (id)
    );

    create table equippable_objects (
        id bigint generated by default as identity,
        power bigint,
        range bigint,
        stealth bigint,
        strength bigint,
        weight bigint,
        description varchar(255),
        name varchar(255) not null unique,
        type varchar(255),
        primary key (id)
    );

    create table items (
        id bigint generated by default as identity,
        price bigint not null,
        description varchar(255),
        name varchar(255) not null unique,
        primary key (id)
    );

    create table parts (
        id bigint generated by default as identity,
        max_health bigint not null,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table paths (
        id bigint generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table ranking_levels (
        id bigint generated by default as identity,
        level bigint not null unique,
        points_required bigint not null,
        description varchar(255),
        primary key (id)
    );

    create table ranks (
        id bigint generated by default as identity,
        level bigint not null unique,
        required_experience bigint not null,
        bonus_descriptions varchar(255),
        primary key (id)
    );

    create table skills (
        is_upgradable boolean,
        id bigint generated by default as identity,
        mental_cost bigint,
        physical_cost bigint,
        required_experience bigint,
        upgrade_level bigint,
        upgrade_points bigint,
        description varchar(255),
        name varchar(255) not null unique,
        primary key (id)
    );

    create table stats (
        abbreviation varchar(3) not null unique,
        id bigint generated by default as identity,
        level_up_experience bigint not null,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table styles (
        id bigint generated by default as identity,
        name varchar(255) not null unique,
        style_class varchar(255) not null unique,
        primary key (id)
    );

    alter table if exists character_parts 
       add constraint FKks74sosw99h4ion8t229aci3j 
       foreign key (character_id) 
       references characters;

    alter table if exists character_parts 
       add constraint FK68ywm1wt4baau1nad9x41029m 
       foreign key (part_id) 
       references parts;

    alter table if exists characters 
       add constraint FK7vg9s6hvmy9u90r7lh3xe7qny 
       foreign key (ranking_id) 
       references ranking_levels;

    create table character_parts (
        character_id bigint not null,
        current_health bigint not null,
        id bigint generated by default as identity,
        part_id bigint not null,
        primary key (id)
    );

    create table characters (
        age bigint not null,
        height bigint not null,
        id bigint generated by default as identity,
        ranking_id bigint not null,
        weight bigint not null,
        gender varchar(255) not null,
        name varchar(255) not null unique,
        race varchar(255) not null check (race in ('KANION','ORTHYS','PUMIBLU','FIERCY','ZI_BUM','LENTILLANO','EYESHADE','LUIN','XYRION','CETARA','DENDROLIAN','KEYUI','UNTOLD','SKETCHE','PRIMAL','ROBOT','OTHER')),
        title varchar(255) not null unique,
        primary key (id)
    );

    create table equippable_objects (
        id bigint generated by default as identity,
        power bigint,
        range bigint,
        stealth bigint,
        strength bigint,
        weight bigint,
        description varchar(255),
        name varchar(255) not null unique,
        type varchar(255),
        primary key (id)
    );

    create table items (
        id bigint generated by default as identity,
        price bigint not null,
        description varchar(255),
        name varchar(255) not null unique,
        primary key (id)
    );

    create table parts (
        id bigint generated by default as identity,
        max_health bigint not null,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table paths (
        id bigint generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table ranking_levels (
        id bigint generated by default as identity,
        level bigint not null unique,
        points_required bigint not null,
        description varchar(255),
        primary key (id)
    );

    create table ranks (
        id bigint generated by default as identity,
        level bigint not null unique,
        required_experience bigint not null,
        bonus_descriptions varchar(255),
        primary key (id)
    );

    create table skills (
        is_upgradable boolean,
        id bigint generated by default as identity,
        mental_cost bigint,
        physical_cost bigint,
        required_experience bigint,
        upgrade_level bigint,
        upgrade_points bigint,
        description varchar(255),
        name varchar(255) not null unique,
        primary key (id)
    );

    create table stats (
        abbreviation varchar(3) not null unique,
        id bigint generated by default as identity,
        level_up_experience bigint not null,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table styles (
        id bigint generated by default as identity,
        name varchar(255) not null unique,
        style_class varchar(255) not null unique,
        primary key (id)
    );

    alter table if exists character_parts 
       add constraint FKks74sosw99h4ion8t229aci3j 
       foreign key (character_id) 
       references characters;

    alter table if exists character_parts 
       add constraint FK68ywm1wt4baau1nad9x41029m 
       foreign key (part_id) 
       references parts;

    alter table if exists characters 
       add constraint FK7vg9s6hvmy9u90r7lh3xe7qny 
       foreign key (ranking_id) 
       references ranking_levels;

    create table character_parts (
        character_id bigint not null,
        current_health bigint not null,
        id bigint generated by default as identity,
        part_id bigint not null,
        primary key (id)
    );

    create table characters (
        age bigint not null,
        height bigint not null,
        id bigint generated by default as identity,
        ranking_id bigint not null,
        weight bigint not null,
        gender varchar(255) not null,
        name varchar(255) not null unique,
        race varchar(255) not null check (race in ('KANION','ORTHYS','PUMIBLU','FIERCY','ZI_BUM','LENTILLANO','EYESHADE','LUIN','XYRION','CETARA','DENDROLIAN','KEYUI','UNTOLD','SKETCHE','PRIMAL','ROBOT','OTHER')),
        title varchar(255) not null unique,
        primary key (id)
    );

    create table equippable_objects (
        id bigint generated by default as identity,
        power bigint,
        range bigint,
        stealth bigint,
        strength bigint,
        weight bigint,
        description varchar(255),
        name varchar(255) not null unique,
        type varchar(255),
        primary key (id)
    );

    create table items (
        id bigint generated by default as identity,
        price bigint not null,
        description varchar(255),
        name varchar(255) not null unique,
        primary key (id)
    );

    create table parts (
        id bigint generated by default as identity,
        max_health bigint not null,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table paths (
        id bigint generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table ranking_levels (
        id bigint generated by default as identity,
        level bigint not null unique,
        points_required bigint not null,
        description varchar(255),
        primary key (id)
    );

    create table ranks (
        id bigint generated by default as identity,
        level bigint not null unique,
        required_experience bigint not null,
        bonus_descriptions varchar(255),
        primary key (id)
    );

    create table skills (
        is_upgradable boolean,
        id bigint generated by default as identity,
        mental_cost bigint,
        physical_cost bigint,
        required_experience bigint,
        upgrade_level bigint,
        upgrade_points bigint,
        description varchar(255),
        name varchar(255) not null unique,
        primary key (id)
    );

    create table stats (
        abbreviation varchar(3) not null unique,
        id bigint generated by default as identity,
        level_up_experience bigint not null,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table styles (
        id bigint generated by default as identity,
        name varchar(255) not null unique,
        style_class varchar(255) not null unique,
        primary key (id)
    );

    alter table if exists character_parts 
       add constraint FKks74sosw99h4ion8t229aci3j 
       foreign key (character_id) 
       references characters;

    alter table if exists character_parts 
       add constraint FK68ywm1wt4baau1nad9x41029m 
       foreign key (part_id) 
       references parts;

    alter table if exists characters 
       add constraint FK7vg9s6hvmy9u90r7lh3xe7qny 
       foreign key (ranking_id) 
       references ranking_levels;

    create table character_parts (
        character_id bigint not null,
        current_health bigint not null,
        id bigint generated by default as identity,
        part_id bigint not null,
        primary key (id)
    );

    create table characters (
        age bigint not null,
        height bigint not null,
        id bigint generated by default as identity,
        ranking_id bigint not null,
        weight bigint not null,
        gender varchar(255) not null,
        name varchar(255) not null unique,
        race varchar(255) not null check (race in ('KANION','ORTHYS','PUMIBLU','FIERCY','ZI_BUM','LENTILLANO','EYESHADE','LUIN','XYRION','CETARA','DENDROLIAN','KEYUI','UNTOLD','SKETCHE','PRIMAL','ROBOT','OTHER')),
        title varchar(255) not null unique,
        primary key (id)
    );

    create table equippable_objects (
        id bigint generated by default as identity,
        power bigint,
        range bigint,
        stealth bigint,
        strength bigint,
        weight bigint,
        description varchar(255),
        name varchar(255) not null unique,
        type varchar(255),
        primary key (id)
    );

    create table items (
        id bigint generated by default as identity,
        price bigint not null,
        description varchar(255),
        name varchar(255) not null unique,
        primary key (id)
    );

    create table parts (
        id bigint generated by default as identity,
        max_health bigint not null,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table paths (
        id bigint generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table ranking_levels (
        id bigint generated by default as identity,
        level bigint not null unique,
        points_required bigint not null,
        description varchar(255),
        primary key (id)
    );

    create table ranks (
        id bigint generated by default as identity,
        level bigint not null unique,
        required_experience bigint not null,
        bonus_descriptions varchar(255),
        primary key (id)
    );

    create table skills (
        is_upgradable boolean,
        id bigint generated by default as identity,
        mental_cost bigint,
        physical_cost bigint,
        required_experience bigint,
        upgrade_level bigint,
        upgrade_points bigint,
        description varchar(255),
        name varchar(255) not null unique,
        primary key (id)
    );

    create table stats (
        abbreviation varchar(3) not null unique,
        id bigint generated by default as identity,
        level_up_experience bigint not null,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table styles (
        id bigint generated by default as identity,
        name varchar(255) not null unique,
        style_class varchar(255) not null unique,
        primary key (id)
    );

    alter table if exists character_parts 
       add constraint FKks74sosw99h4ion8t229aci3j 
       foreign key (character_id) 
       references characters;

    alter table if exists character_parts 
       add constraint FK68ywm1wt4baau1nad9x41029m 
       foreign key (part_id) 
       references parts;

    alter table if exists characters 
       add constraint FK7vg9s6hvmy9u90r7lh3xe7qny 
       foreign key (ranking_id) 
       references ranking_levels;
