spring:
  application:
    name: character-bff-service-test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    console:
      enabled: true
      path: /h2-console

wiremock:
  server:
    port: 8089

logging:
  level:
    org.springframework: DEBUG
    com.kanionland: DEBUG
    feign: DEBUG

jwt:
  secret: ${JWT_SECRET:31qRand0mdYSYgM=}
