CREATE TABLE IF NOT EXISTS characters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    race VARCHAR(50) NOT NULL,
    title VARCHAR(255),
    gender VARCHAR(50),
    age BIGINT,
    weight BIGINT,
    height BIGINT,
    ranking_id BIGINT
);

CREATE TABLE IF NOT EXISTS parts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    max_health BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS character_parts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character_id BIGINT NOT NULL,
    current_health BIGINT NOT NULL,
    part_id BIGINT NOT NULL,
    FOREIGN KEY (part_id) REFERENCES parts(id),
    FOREIGN KEY (character_id) REFERENCES characters(id)
);


INSERT INTO parts (max_health, name) VALUES (100, 'Head');
INSERT INTO parts (max_health, name) VALUES (100, 'Torso');
INSERT INTO parts (max_health, name) VALUES (100, 'Left Arm');
INSERT INTO parts (max_health, name) VALUES (100, 'Right Arm');
INSERT INTO parts (max_health, name) VALUES (100, 'Left Leg');
INSERT INTO parts (max_health, name) VALUES (100, 'Right Leg');
INSERT INTO parts (max_health, name) VALUES (100, 'Left Ear-Arm');
INSERT INTO parts (max_health, name) VALUES (100, 'Right Ear-Arm');
INSERT INTO parts (max_health, name) VALUES (100, 'Tail');
INSERT INTO parts (max_health, name) VALUES (100, 'Left Wing');
INSERT INTO parts (max_health, name) VALUES (100, 'Right Wing');
INSERT INTO parts (max_health, name) VALUES (100, 'Eye');
INSERT INTO parts (max_health, name) VALUES (100, 'Equine Torso');
INSERT INTO parts (max_health, name) VALUES (100, 'Engine');