name: Maven CI - Test, Verify and Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and test with Maven
        run: |
          mvn clean test jacoco:report -Dmaven.test.failure.ignore=true

      - name: Check code coverage
        run: |
          mvn jacoco:check
        continue-on-error: true

      - name: Generate site reports
        run: |
          mvn site site:stage
        continue-on-error: true

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: |
            target/surefire-reports
            target/site
          retention-days: 2

      - name: Set build status based on test results
        if: steps.build.outcome != 'success'
        run: exit 1